### ISSUE TITLE
Bugged before start

### ISSUE THREAD

**Issue by matibaski** [andraskende/cakephp-3-shopping-cart#2]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.5.6
* Platform and Target: XAMPP Apache 2.4, MySQL, PHP 7.2.8

### What you did
Downloaded your cakePHP skeleton, installed it (running on PHP 7.2.8). Changed database configuration in `app.php` and imported the SQL file to my MySQL database.

### What happened
```
method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;App\Model\Entity\Profile&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition 
File ...\vendor\cakephp\debug_kit\src\Panel\VariablesPanel.php 
```

### What you expected to happen
A running standard instance.

**Comment by andraskende** [comment]
Hello,

Did you install with composer ?
composer create-project --prefer-dist -s dev andraskende/cakephp-3-shopping-cart www

Could you install a plain cakephp 3 on your server ?

Just installed on ubuntu18 php7 its worked fine., but I will update to latest cake version in a few days...

Thanks,
Andras

**Comment by matibaski** [comment]
Installed it via composer. Weirdly, it just started working after restarting apache and mysql.
